apiVersion: networking.k8s.io/v1
kind: NetworkPolicies
metadata:
  name: my-default
  namespace: default
spec:
  podSelector: 
    matchLabels:
      app: webapp
  policyTypes:
  - Ingress
  ingress:
  - from
    - podSelector:
        matchLabels:
          app: webapp